### SIGN UP
POST http://localhost:1818/signup HTTP/1.1
Content-Type: application/json

{
    "email": "tilde@zmail.com",
    "username": "tilde",
    "password": "pasta"
}

### Verify
GET http://localhost:1818/verify HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJ1c2VybmFtZSI6ImhpbG1vIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MzYzODYzOTEsImV4cCI6MTYzNjM4Njk5MX0.CgGQuMGW8wO1v8BQ30xjNWciZGhNCxjiYuLF-n5b_hA